### PR TITLE
Bring mirror up to date with 2022.1 release

### PR DESCRIPTION
**Pull request by douglaskastle**
There have been 4 releases since the last time the main branch was up to date.

grlib-gpl-2020.4-b4261 - 2020-12-09 - http://www.gaisler.com/products/grlib/grlib-gpl-2020.4-b4261.tar.gz
grlib-gpl-2021.1-b4265 - 2021-04-06 - http://www.gaisler.com/products/grlib/grlib-gpl-2021.1-b4265.tar.gz
grlib-gpl-2021.2-b4267 - 2021-06-30 - http://www.gaisler.com/products/grlib/grlib-gpl-2021.2-b4267.tar.gz
grlib-gpl-2022.1-b4272 - 2022-03-01 - http://www.gaisler.com/products/grlib/grlib-gpl-2022.1-b4272.tar.gz

This add those release and tags each stage:

git tag -a grlib-gpl-2022.1-b4272 https://github.com/TUT-ASI/leon3-grlib-gpl-mirror/commit/687ed3165d976ed88c938b9079de2d5ad777eadf
git tag -a grlib-gpl-2021.2-b4267 https://github.com/TUT-ASI/leon3-grlib-gpl-mirror/commit/4444688d213fece7fe48b1e2b35fc4760a497233
git tag -a grlib-gpl-2021.1-b4265 https://github.com/TUT-ASI/leon3-grlib-gpl-mirror/commit/a1cfcd1eb649e3be1639cc2a13b149147246c5a6
git tag -a grlib-gpl-2020.4-b4261 https://github.com/TUT-ASI/leon3-grlib-gpl-mirror/commit/2a17a37a4f780b371c037e82c2043639ca31fa9d

### CODE REVIEW

**Comment by AlexDaniel** [comment]
Thank you! Sorry for not keeping it up to date, I have always been wondering if anybody is using it :) Let me know if merging this earlier will make things easier for you right now, otherwise I'll do it on Thursday (which is when I'll be back home).

**Comment by douglaskastle** [comment]
No rush here, just catching up myself.

**Comment by douglaskastle** [comment]
Sorry closed the PR by accident, reopened

**Comment by douglaskastle** [comment]
bump

**Comment by AlexDaniel** [comment]
@douglaskastle Thanks for the bump, sorry for the delay!

The repo should now be up to date. Please check that everything looks fine.

For the record, I just run this script that I wrote a long time ago and it creates all of the commits automatically:

```raku
#!/usr/bin/env raku

# TODO MULTIPLE ORIGINS

# Crude but works ↓
my $url  = ‘https://www.gaisler.com/index.php/downloads/leongrlib’;
my $page = run(:out, <curl -->, $url).out.slurp;
my $line = $page.lines.grep(/｢<a href="/products/grlib/grlib-gpl｣/).head;

my ($tar-link, $changelog-link) = ($line ~~ m:g/‘href="’(<-["]>+)‘"’/)»[0]».Str;

run <curl --remote-name -->, ‘https://www.gaisler.com’~$changelog-link;
run <curl --remote-name -->, ‘https://www.gaisler.com’~$tar-link, :cwd(‘snapshots’);

my @snapshots = dir ‘snapshots’;
@snapshots .= map: { die unless /‘-b’(\d+)‘.tar.gz’$ /; +$0 => $_ };
@snapshots .= sort: *.key;

my $changelog = ‘Changelog.txt’.IO.slurp ~ “\n” ~ ‘Changelog-old.txt’.IO.slurp;

my @changelog-chunks = reverse $changelog.split: /<before ^^‘--’>/, :skip-empty;

@changelog-chunks .= map: {
    /\N*‘-b’(\d+)‘ --’/
    ?? (+$0 => $_)
    !! (--$ => $_) # some really old stuff
}

my $changelog-counter = 0;

my $last-date = ‘2010-02-01’;

for @snapshots {
    note “Processing b”, .key;
    my $archive = .value;
    my $extracted = $archive.extension: ‘’, :2parts;
    my $name = $extracted.basename;

    my $changelog = ‘’;
    my @hits; # to keep track of revisions that are not available
    for @changelog-chunks[$changelog-counter..∞] -> $log {
        last if $log.key > .key;
        $changelog [R~]= $log.value;
        @hits.push: @changelog-chunks.shift
    }

    my $date = ($changelog ~~ /\d\d\d\d‘-’\d\d‘-’\d\d/); # whatever we find first
    $date  //= $last-date;
    $date .= Str;
    $last-date = $date;

    # TODO maybe use File::Directory::Tree ?
    if ‘repo’.IO.e.not {
        mkdir ‘repo’;
        run :cwd(‘repo’), <git init>
    }
    if run :err(Nil), :cwd(‘repo’), <git rev-parse>, $name {
        note “$name already committed, skipping”;
        next
    }

    rename ‘repo’, ‘old-repo’;

    run <tar -xf>, $archive, ‘-C’, $extracted.parent;
    run <cp -a>, $extracted.add(‘.’), ‘repo’;
    die ‘Git repo in the archive’ if ‘repo/.git’.IO.e;
    run <cp -r old-repo/.git repo>;
    if ‘old-repo/README.md’.IO.e {
        copy ‘old-repo/README.md’, ‘repo/README.md’
    } else {
        copy ‘README.md’, ‘repo/README.md’
    }
    run <rm -rf old-repo>;
    run <rm -rf>, $extracted;

    my @readme-entries;
    my $main-visited = False;
    for @hits {
        die unless .value ~~ /^‘-’+\s+‘Release’\s+(\S+)\s+‘-’+$$/;
        my $hit-name = “grlib-gpl-$0”;
        if $hit-name eq $name {
            $main-visited = True;
            next
        }
        @readme-entries.push: sprintf “| % -25s|    % -8s|”, $hit-name, ‘No’;
    }
    @readme-entries.push: sprintf “| % -25s|    % -8s|”, $name, $main-visited ?? ‘Yes’ !! ‘Yes¹’;
    my $readme = slurp ‘repo/README.md’;
    die ‘Weird README’ unless $readme ~~ s/<after “--------|\n”>/{@readme-entries.reverse.join: “\n”}\n/;
    spurt ‘repo/README.md’, $readme;

    run :cwd(‘repo’), <git add -A>;
    run :cwd(‘repo’), <git commit -m>, “$name\n\n$changelog”, “--date={$date}T00:00:00+00:00”, ‘--author=Gaisler <>’;

    #run :cwd(‘repo’), <git tag -a>, $name, ‘-m’, $changelog; # annotated
    run :cwd(‘repo’), <git tag>, $name; # lightweight
}

$ = so run :cwd(‘repo’), <git remote set-url origin --add git@github.com:TUT-ASI/leon3-grlib-gpl-mirror.git>;

run :cwd(‘repo’), <git push -u origin master>;
run :cwd(‘repo’), <git push --tags>;
```

I believe you achieved the same thing in this PR by hand. The result should be exactly the same, but GitHub is getting a bit confused about the diff between your branch and master. Both should contain exactly the same files though.

Anyway, please let me know if there's any issue!

**Comment by douglaskastle** [comment]
Cool, that script would have been handy.

It didn't take that long to do by hand though.

**Pull request closed without merging**
